import js from '@eslint/js';
import tseslint from '@typescript-eslint/eslint-plugin';
import tsparser from '@typescript-eslint/parser';

export default [
  js.configs.recommended,
  {
    files: ['src/**/*.ts'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        project: './tsconfig.json',
      },
      globals: {
        console: 'readonly',
        ReadableStream: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        TransformStream: 'readonly',
        WritableStream: 'readonly',
        CompressionStream: 'readonly',
        DecompressionStream: 'readonly',
        Uint8Array: 'readonly',
        Uint16Array: 'readonly',
        Uint32Array: 'readonly',
        ArrayBuffer: 'readonly',
        Buffer: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        crypto: 'readonly',
        __dirname: 'readonly',
        BufferEncoding: 'readonly',
        TransformStreamDefaultController: 'readonly',
        WritableStream: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': 'off',
      'no-unused-vars': 'off',
      'no-unreachable': 'off',
      'no-undef': 'off',
      '@typescript-eslint/explicit-function-return-type': 'warn',
      '@typescript-eslint/strict-boolean-expressions': 'warn',
      '@typescript-eslint/switch-exhaustiveness-check': 'off',
      '@typescript-eslint/prefer-readonly': 'warn',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/await-thenable': 'off',
      'require-yield': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      'no-redeclare': 'off',
      'max-depth': ['warn', 5],
      complexity: ['warn', 15],
      'max-nested-callbacks': ['warn', 5],
      'max-params': ['warn', 6],
      'max-lines-per-function': ['warn', 100],
      'no-console': 'off',
      'prefer-const': 'error',
      'no-var': 'error',
      'no-implied-eval': 'error',
      'no-new-wrappers': 'error',
      'no-throw-literal': 'error',
      'no-magic-numbers': 'off',
    },
  },
  {
    files: ['test/**/*.ts'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        console: 'readonly',
        Buffer: 'readonly',
        Uint8Array: 'readonly',
        ReadableStream: 'readonly',
        TransformStream: 'readonly',
        WritableStream: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        process: 'readonly',
        performance: 'readonly',
        global: 'readonly',
        setTimeout: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        describe: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        it: 'readonly',
        Bun: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': 'off',
      'no-unused-vars': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      'max-lines-per-function': 'off',
      'no-magic-numbers': 'off',
      'prefer-const': 'error',
      'no-var': 'error',
      'no-redeclare': 'off',
      'no-useless-escape': 'off',
      'no-undef': 'off',
    },
  },
  {
    ignores: ['dist/**/*', 'node_modules/**/*', 'src/zig/**/*', '*.js', '*.d.ts'],
  },
];
