/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Stateful alignment file reader exposed to TypeScript.
 *
 * Wraps a noodles BAM or SAM reader. The file handle, decompression
 * state (for BAM), and parsed header are owned by this struct and
 * live on the JS heap until garbage collected.
 */
export declare class AlignmentReader {
  /**
   * Open a BAM or SAM file for reading.
   *
   * Format is detected by reading the first few bytes: if they
   * match the BGZF magic (`1f 8b`), the file is treated as BAM;
   * otherwise it is treated as SAM.
   *
   * The header is read immediately. Records are read lazily via
   * `readBatch`.
   * Open a BAM or SAM file for reading.
   *
   * The file is opened once. Format is detected by reading the
   * first two bytes and checking for the BGZF/gzip magic number,
   * then seeking back to the start before handing the file handle
   * to the appropriate noodles reader.
   *
   * The header is read immediately. Records are read lazily via
   * `readBatch`.
   */
  static open(path: string): AlignmentReader
  /**
   * Open a BAM or SAM dataset from an in-memory buffer.
   *
   * Format is detected from the first two bytes, same as `open`.
   * This is used by the TypeScript `parseString` and `parse`
   * methods to avoid writing to a temp file.
   */
  static openBytes(data: Buffer): AlignmentReader
  /**
   * Read the next batch of alignment records.
   *
   * Returns up to `max_records` records, or `None` when all
   * records have been consumed.
   */
  readBatch(maxRecords: number): AlignmentBatch | null
  /** Get the raw SAM header text. */
  headerText(): string
  /** Get the reference sequence dictionary from the header. */
  referenceSequences(): Array<ReferenceSequenceInfo>
}

/**
 * A batch of parsed alignment records in struct-of-arrays layout.
 *
 * Variable-length fields use the packed-bytes-plus-offsets convention
 * established by the existing batch kernels. Fixed-width fields use
 * flat typed arrays with one element per record.
 */
export interface AlignmentBatch {
  /** Number of records in this batch. */
  count: number
  /** Source format for all records in this batch ("bam" or "sam"). */
  format: string
  /** Concatenated read name bytes (UTF-8). */
  qnameData: Buffer
  /** N+1 offsets into `qname_data`. */
  qnameOffsets: Array<number>
  /** Concatenated decoded sequence bytes (ASCII). */
  sequenceData: Buffer
  /** N+1 offsets into `sequence_data`. */
  sequenceOffsets: Array<number>
  /** Concatenated quality bytes (Phred+33 ASCII). */
  qualityData: Buffer
  /** N+1 offsets into `quality_data`. */
  qualityOffsets: Array<number>
  /** Concatenated CIGAR string bytes (UTF-8). */
  cigarData: Buffer
  /** N+1 offsets into `cigar_data`. */
  cigarOffsets: Array<number>
  /** Concatenated reference sequence name bytes (UTF-8). */
  rnameData: Buffer
  /** N+1 offsets into `rname_data`. */
  rnameOffsets: Array<number>
  /** SAM flags (one u16 per record). */
  flags: Array<number>
  /** 1-based positions (one i32 per record; 0 if unmapped). */
  positions: Array<number>
  /** Mapping qualities (one u8 per record; 255 if unavailable). */
  mappingQualities: Buffer
}

export declare function checkValidBatch(sequences: Uint8Array, offsets: Uint32Array, mode: ValidationMode): Buffer

export declare function classifyBatch(sequences: Uint8Array, offsets: Uint32Array): ClassifyResult

export interface ClassifyResult {
  counts: Array<number>
}

export declare function findPatternBatch(sequences: Uint8Array, offsets: Uint32Array, pattern: Uint8Array, maxEdits: number, caseInsensitive: boolean): PatternSearchResult

export declare function grepBatch(sequences: Uint8Array, offsets: Uint32Array, pattern: Uint8Array, maxEdits: number, caseInsensitive: boolean, searchBothStrands: boolean): Buffer

export declare function hashBatch(sequences: Uint8Array, offsets: Uint32Array, caseInsensitive: boolean): Buffer

export interface PatternSearchResult {
  starts: Array<number>
  ends: Array<number>
  costs: Array<number>
  matchOffsets: Array<number>
}

export declare function qualityAvgBatch(quality: Uint8Array, offsets: Uint32Array, asciiOffset: number): Array<number>

export declare function qualityBinBatch(quality: Uint8Array, offsets: Uint32Array, boundaries: Uint8Array, representatives: Uint8Array): TransformResult

export declare function qualityTrimBatch(quality: Uint8Array, offsets: Uint32Array, asciiOffset: number, threshold: number, windowSize: number, trimStart: boolean, trimEnd: boolean): Array<number>

/** Information about a reference sequence from the SAM/BAM header. */
export interface ReferenceSequenceInfo {
  name: string
  length: number
}

export declare function removeGapsBatch(sequences: Uint8Array, offsets: Uint32Array, gapChars: string): TransformResult

export declare function replaceAmbiguousBatch(sequences: Uint8Array, offsets: Uint32Array, replacement: string): TransformResult

export declare function replaceInvalidBatch(sequences: Uint8Array, offsets: Uint32Array, mode: ValidationMode, replacement: string): TransformResult

export declare function sequenceMetricsBatch(sequences: Uint8Array, seqOffsets: Uint32Array, quality: Uint8Array, qualOffsets: Uint32Array, metricFlags: number, asciiOffset: number): SequenceMetricsResult

export interface SequenceMetricsResult {
  lengths?: Array<number>
  gc?: Array<number>
  at?: Array<number>
  gcSkew?: Array<number>
  atSkew?: Array<number>
  entropy?: Array<number>
  alphabetMask?: Array<number>
  avgQual?: Array<number>
  minQual?: Array<number>
  maxQual?: Array<number>
}

export declare function transformBatch(sequences: Uint8Array, offsets: Uint32Array, op: TransformOp): TransformResult

export declare const enum TransformOp {
  Complement = 'Complement',
  ComplementRna = 'ComplementRna',
  Reverse = 'Reverse',
  ReverseComplement = 'ReverseComplement',
  ReverseComplementRna = 'ReverseComplementRna',
  ToRna = 'ToRna',
  ToDna = 'ToDna',
  UpperCase = 'UpperCase',
  LowerCase = 'LowerCase'
}

export interface TransformResult {
  data: Buffer
  offsets: Array<number>
}

export declare function translateBatch(sequences: Uint8Array, offsets: Uint32Array, translationLut: Uint8Array, startMask: Uint8Array, alternativeStartMask: Uint8Array, options: TranslateBatchOptions): TransformResult

export interface TranslateBatchOptions {
  frameOffset: number
  reverse: boolean
  convertStartCodons: boolean
  allowAlternativeStarts: boolean
  trimAtFirstStop: boolean
  removeStopCodons: boolean
  stopCodonChar: string
  unknownCodonChar: string
}

export declare const enum ValidationMode {
  StrictDna = 'StrictDna',
  NormalDna = 'NormalDna',
  StrictRna = 'StrictRna',
  NormalRna = 'NormalRna',
  Protein = 'Protein'
}
