/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AlignmentReader {
  static open(path: string): AlignmentReader
  static openBytes(data: Buffer): AlignmentReader
  readBatch(maxRecords: number): AlignmentBatch | null
  headerText(): string
  referenceSequences(): Array<ReferenceSequenceInfo>
}

export declare class FastaReader {
  static open(path: string): FastaReader
  static openBytes(data: Buffer): FastaReader
  readBatch(maxRecords: number): FastaBatch | null
}

export declare class FastaWriter {
  static open(path: string, compress: boolean, lineWidth: number): FastaWriter
  static openBytes(compress: boolean, lineWidth: number): FastaWriter
  writeBatch(nameData: Uint8Array, nameOffsets: Uint32Array, descriptionData: Uint8Array, descriptionOffsets: Uint32Array, sequenceData: Uint8Array, sequenceOffsets: Uint32Array, count: number): void
  finish(): Buffer | null
}

export declare class FastqReader {
  static open(path: string): FastqReader
  static openBytes(data: Buffer): FastqReader
  readBatch(maxRecords: number): FastqBatch | null
}

export declare class FastqWriter {
  static open(path: string, compress: boolean): FastqWriter
  static openBytes(compress: boolean): FastqWriter
  writeBatch(nameData: Uint8Array, nameOffsets: Uint32Array, descriptionData: Uint8Array, descriptionOffsets: Uint32Array, sequenceData: Uint8Array, sequenceOffsets: Uint32Array, qualityData: Uint8Array, qualityOffsets: Uint32Array, count: number): void
  finish(): Buffer | null
}

export interface AlignmentBatch {
  count: number
  format: string
  qnameData: Buffer
  qnameOffsets: Array<number>
  sequenceData: Buffer
  sequenceOffsets: Array<number>
  qualityData: Buffer
  qualityOffsets: Array<number>
  cigarData: Buffer
  cigarOffsets: Array<number>
  rnameData: Buffer
  rnameOffsets: Array<number>
  flags: Array<number>
  positions: Array<number>
  mappingQualities: Buffer
}

export declare function checkValidBatch(sequences: Uint8Array, offsets: Uint32Array, mode: ValidationMode): Buffer

export declare function classifyBatch(sequences: Uint8Array, offsets: Uint32Array): ClassifyResult

export interface ClassifyResult {
  counts: Array<number>
}

export interface FastaBatch {
  count: number
  nameData: Buffer
  nameOffsets: Array<number>
  descriptionData: Buffer
  descriptionOffsets: Array<number>
  sequenceData: Buffer
  sequenceOffsets: Array<number>
}

export interface FastqBatch {
  count: number
  nameData: Buffer
  nameOffsets: Array<number>
  descriptionData: Buffer
  descriptionOffsets: Array<number>
  sequenceData: Buffer
  sequenceOffsets: Array<number>
  qualityData: Buffer
  qualityOffsets: Array<number>
}

export declare function findPatternBatch(sequences: Uint8Array, offsets: Uint32Array, pattern: Uint8Array, maxEdits: number, caseInsensitive: boolean): PatternSearchResult

export declare function grepBatch(sequences: Uint8Array, offsets: Uint32Array, pattern: Uint8Array, maxEdits: number, caseInsensitive: boolean, searchBothStrands: boolean): Buffer

export declare function hashBatch(sequences: Uint8Array, offsets: Uint32Array, caseInsensitive: boolean): Buffer

export interface PatternSearchResult {
  starts: Array<number>
  ends: Array<number>
  costs: Array<number>
  matchOffsets: Array<number>
}

export declare function qualityAvgBatch(quality: Uint8Array, offsets: Uint32Array, asciiOffset: number): Array<number>

export declare function qualityBinBatch(quality: Uint8Array, offsets: Uint32Array, boundaries: Uint8Array, representatives: Uint8Array): TransformResult

export declare function qualityTrimBatch(quality: Uint8Array, offsets: Uint32Array, asciiOffset: number, threshold: number, windowSize: number, trimStart: boolean, trimEnd: boolean): Array<number>

export interface ReferenceSequenceInfo {
  name: string
  length: number
}

export declare function removeGapsBatch(sequences: Uint8Array, offsets: Uint32Array, gapChars: string): TransformResult

export declare function replaceAmbiguousBatch(sequences: Uint8Array, offsets: Uint32Array, replacement: string): TransformResult

export declare function replaceInvalidBatch(sequences: Uint8Array, offsets: Uint32Array, mode: ValidationMode, replacement: string): TransformResult

export declare function sequenceMetricsBatch(sequences: Uint8Array, seqOffsets: Uint32Array, quality: Uint8Array, qualOffsets: Uint32Array, metricFlags: number, asciiOffset: number): SequenceMetricsResult

export interface SequenceMetricsResult {
  lengths?: Array<number>
  gc?: Array<number>
  at?: Array<number>
  gcSkew?: Array<number>
  atSkew?: Array<number>
  entropy?: Array<number>
  alphabetMask?: Array<number>
  avgQual?: Array<number>
  minQual?: Array<number>
  maxQual?: Array<number>
}

export declare function transformBatch(sequences: Uint8Array, offsets: Uint32Array, op: TransformOp): TransformResult

export declare const enum TransformOp {
  Complement = 'Complement',
  ComplementRna = 'ComplementRna',
  Reverse = 'Reverse',
  ReverseComplement = 'ReverseComplement',
  ReverseComplementRna = 'ReverseComplementRna',
  ToRna = 'ToRna',
  ToDna = 'ToDna',
  UpperCase = 'UpperCase',
  LowerCase = 'LowerCase'
}

export interface TransformResult {
  data: Buffer
  offsets: Array<number>
}

export declare function translateBatch(sequences: Uint8Array, offsets: Uint32Array, translationLut: Uint8Array, startMask: Uint8Array, alternativeStartMask: Uint8Array, options: TranslateBatchOptions): TransformResult

export interface TranslateBatchOptions {
  frameOffset: number
  reverse: boolean
  convertStartCodons: boolean
  allowAlternativeStarts: boolean
  trimAtFirstStop: boolean
  removeStopCodons: boolean
  stopCodonChar: string
  unknownCodonChar: string
}

export declare const enum ValidationMode {
  StrictDna = 'StrictDna',
  NormalDna = 'NormalDna',
  StrictRna = 'StrictRna',
  NormalRna = 'NormalRna',
  Protein = 'Protein'
}
